apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-nexus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kunals30/sampleproject-gitops
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: sampleproject
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
